// 20 SEO-optimized blog posts (one per tool)
export const blogs = [
  {
    id: 'compress-image-guide',
    title: 'How to Compress Images Online for Free — The Complete Guide',
    slug: 'compress-image-guide',
    category: 'Optimize',
    author: 'Pixalyse Team',
    date: '2025-12-15',
    readTime: 8,
    image: 'compress.jpg',
    excerpt: 'Learn how to reduce image file size without losing quality using modern compression techniques.',
    content: `Image compression is essential for faster websites and smaller file transfers. This guide covers PNG vs JPG compression, quality settings, and best practices...`,
  },
  {
    id: 'bulk-compress-tutorial',
    title: 'Bulk Compress Multiple Images at Once — Save Time & Storage',
    slug: 'bulk-compress-tutorial',
    category: 'Optimize',
    author: 'Pixalyse Team',
    date: '2025-12-14',
    readTime: 6,
    image: 'bulk.jpg',
    excerpt: 'Compress multiple images simultaneously and save hours of manual work.',
    content: `Processing hundreds of images individually is time-consuming. Discover how to bulk compress and optimize your entire image library...`,
  },
  {
    id: 'image-resizing-best-practices',
    title: 'Image Resizing Guide: Perfect Dimensions for Web, Social & Print',
    slug: 'image-resizing-best-practices',
    category: 'Edit',
    author: 'Pixalyse Team',
    date: '2025-12-13',
    readTime: 7,
    image: 'resize.jpg',
    excerpt: 'Master image dimensions for every platform with our comprehensive sizing guide.',
    content: `Different platforms require different image sizes. Learn optimal dimensions for Instagram, Twitter, LinkedIn, websites, and print materials...`,
  },
  {
    id: 'how-to-crop-photos',
    title: 'How to Crop Photos Online — Rule of Thirds & Composition Tips',
    slug: 'how-to-crop-photos',
    category: 'Edit',
    author: 'Pixalyse Team',
    date: '2025-12-12',
    readTime: 6,
    image: 'crop.jpg',
    excerpt: 'Learn professional cropping techniques to improve composition and focus.',
    content: `Good composition starts with proper cropping. Master the rule of thirds, leading lines, and focal point positioning...`,
  },
  {
    id: 'rotate-flip-guide',
    title: 'How to Rotate and Flip Images — Orientation Guide for All Formats',
    slug: 'rotate-flip-guide',
    category: 'Edit',
    author: 'Pixalyse Team',
    date: '2025-12-11',
    readTime: 5,
    image: 'rotate.jpg',
    excerpt: 'Fix image orientation issues with rotation and flip tools.',
    content: `Accidentally took photos at the wrong angle? Learn how to rotate and flip images correctly...`,
  },
  {
    id: 'watermark-protection-guide',
    title: 'How to Add Watermarks to Protect Your Images Online',
    slug: 'watermark-protection-guide',
    category: 'Edit',
    author: 'Pixalyse Team',
    date: '2025-12-10',
    readTime: 7,
    image: 'watermark.jpg',
    excerpt: 'Protect your creative work by adding professional watermarks.',
    content: `Watermarks help protect intellectual property and brand images. Learn positioning, opacity, and font selection best practices...`,
  },
  {
    id: 'png-to-jpg-conversion',
    title: 'PNG to JPG — When to Convert & Quality Comparison',
    slug: 'png-to-jpg-conversion',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-09',
    readTime: 8,
    image: 'formats.jpg',
    excerpt: 'Understand the differences between PNG and JPG formats.',
    content: `PNG and JPG have different strengths. Learn when to use each format, quality differences, and how conversion affects file size...`,
  },
  {
    id: 'webp-format-guide',
    title: 'WebP Image Format — Modern Web Format for Faster Loading',
    slug: 'webp-format-guide',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-08',
    readTime: 8,
    image: 'webp.jpg',
    excerpt: 'Discover how WebP improves website performance and load times.',
    content: `WebP is 25-35% smaller than JPG/PNG while maintaining quality. Learn browser support, implementation, and optimization strategies...`,
  },
  {
    id: 'heic-format-explained',
    title: 'HEIC Format Explained — iPhone Photos to Universal JPG Conversion',
    slug: 'heic-format-explained',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-07',
    readTime: 7,
    image: 'heic.jpg',
    excerpt: 'Convert iPhone HEIC images to JPG for universal compatibility.',
    content: `HEIC is Apple's modern format, but not universally supported. Learn why convert to JPG, compatibility issues, and best practices...`,
  },
  {
    id: 'svg-rasterization-guide',
    title: 'SVG to PNG — When & How to Rasterize Vector Graphics',
    slug: 'svg-rasterization-guide',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-06',
    readTime: 6,
    image: 'svg.jpg',
    excerpt: 'Convert vector SVG graphics to raster PNG format.',
    content: `SVG and PNG serve different purposes. Learn when to convert SVG to PNG, quality implications, and preservation techniques...`,
  },
  {
    id: 'image-to-pdf-conversion',
    title: 'Convert Images to PDF — Create PDFs from JPG, PNG & More',
    slug: 'image-to-pdf-conversion',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-05',
    readTime: 7,
    image: 'pdf.jpg',
    excerpt: 'Easily convert images into PDF documents.',
    content: `Converting images to PDF is useful for documentation, archiving, and sharing. Learn quality settings, page orientation, and compression...`,
  },
  {
    id: 'pdf-to-image-extraction',
    title: 'Extract Images from PDF — Convert PDF Pages to JPG',
    slug: 'pdf-to-image-extraction',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-04',
    readTime: 6,
    image: 'pdf-extract.jpg',
    excerpt: 'Extract images from PDF files quickly and easily.',
    content: `Need to extract images from PDFs? Learn batch extraction, resolution preservation, and quality optimization...`,
  },
  {
    id: 'gif-to-video-conversion',
    title: 'Convert GIF to MP4 — Reduce File Size by 90%',
    slug: 'gif-to-video-conversion',
    category: 'Convert',
    author: 'Pixalyse Team',
    date: '2025-12-03',
    readTime: 7,
    image: 'gif-mp4.jpg',
    excerpt: 'Convert animated GIFs to MP4 video format for smaller files.',
    content: `MP4 video is dramatically smaller than GIF while maintaining animation. Learn encoding, browser support, and implementation...`,
  },
  {
    id: 'image-upscaling-ai',
    title: 'AI Image Upscaling — Enlarge Photos Without Quality Loss',
    slug: 'image-upscaling-ai',
    category: 'AI Tools',
    author: 'Pixalyse Team',
    date: '2025-12-02',
    readTime: 8,
    image: 'upscale.jpg',
    excerpt: 'Use AI to enlarge and enhance low-resolution images.',
    content: `AI upscaling has revolutionized image enlargement. Learn how neural networks reconstruct detail, 2x-4x enlargement, and best uses...`,
  },
  {
    id: 'blur-background-photography',
    title: 'Blur Background Online — Create Depth of Field Effect',
    slug: 'blur-background-photography',
    category: 'AI Tools',
    author: 'Pixalyse Team',
    date: '2025-12-01',
    readTime: 6,
    image: 'blur-bg.jpg',
    excerpt: 'Add professional background blur effect to any photo.',
    content: `Background blur creates professional portraits and product photos. Learn intensity control, edge detection, and creative applications...`,
  },
  {
    id: 'remove-background-ai',
    title: 'Remove Background from Photos — AI-Powered Image Editing',
    slug: 'remove-background-ai',
    category: 'AI Tools',
    author: 'Pixalyse Team',
    date: '2025-11-30',
    readTime: 8,
    image: 'remove-bg.jpg',
    excerpt: 'Remove image backgrounds automatically with AI.',
    content: `AI background removal saves hours of manual editing. Learn accuracy, transparent output, edge refinement, and best practices...`,
  },
  {
    id: 'image-to-base64-encoding',
    title: 'Image to Base64 — Encode Images for Web Development',
    slug: 'image-to-base64-encoding',
    category: 'Developer',
    author: 'Pixalyse Team',
    date: '2025-11-29',
    readTime: 6,
    image: 'base64.jpg',
    excerpt: 'Convert images to Base64 for embedded web usage.',
    content: `Base64 encoding embeds images in HTML/CSS. Learn when to use, data URI format, file size impact, and optimization...`,
  },
  {
    id: 'passport-photo-guide',
    title: 'Create Passport Photos Online — Size & Requirements Guide',
    slug: 'passport-photo-guide',
    category: 'Special',
    author: 'Pixalyse Team',
    date: '2025-11-28',
    readTime: 7,
    image: 'passport.jpg',
    excerpt: 'Create official passport photos with correct dimensions.',
    content: `Passport photos have strict size and composition requirements. Learn international standards, background rules, and formatting...`,
  },
  {
    id: 'screenshot-to-pdf-guide',
    title: 'Convert Screenshot to PDF — Batch Export & Archive',
    slug: 'screenshot-to-pdf-guide',
    category: 'Special',
    author: 'Pixalyse Team',
    date: '2025-11-27',
    readTime: 5,
    image: 'screenshot.jpg',
    excerpt: 'Convert screenshots into shareable PDF documents.',
    content: `Turn screenshots into professional PDFs for documentation. Learn batch processing, compression, and organization...`,
  },
];
