// ─────────────────────────────────────────────────────────────────────────────
// ENGINE 5: GEOGRAPHIC EXPANSION
// 5 language landing pages — India (Hindi), Brazil (Portuguese),
// Spain/LATAM (Spanish), Indonesia (Indonesian), Arab World (Arabic)
// Each targets the highest-volume keywords in that language
// ─────────────────────────────────────────────────────────────────────────────

export const LANGUAGES = {

  // ─── HINDI (India) ──────────────────────────────────────────────────────
  hi: {
    lang: "hi",
    dir: "ltr",
    slug: "hi",
    htmlLang: "hi-IN",
    country: "India",
    flag: "🇮🇳",
    seoTitle: "Pixalyse — मुफ़्त ऑनलाइन इमेज टूल्स | इमेज कम्प्रेस, रिसाइज़, कन्वर्ट करें",
    seoDesc: "20 मुफ़्त ऑनलाइन इमेज टूल्स — इमेज कम्प्रेस करें, रिसाइज़ करें, PNG से JPG कन्वर्ट करें, HEIC से JPG। कोई लॉगिन नहीं, कोई वॉटरमार्क नहीं। ब्राउज़र में काम करता है।",
    seoKeywords: "इमेज कम्प्रेस करें मुफ्त, image compress karo free, heic to jpg hindi, png to jpg converter hindi, image resize online free india, compress image whatsapp hindi",
    headline: "20 मुफ़्त इमेज टूल्स",
    subheadline: "इमेज कम्प्रेस, रिसाइज़, क्रॉप, कन्वर्ट करें — बिल्कुल मुफ़्त",
    tagline: "कोई लॉगिन नहीं · कोई वॉटरमार्क नहीं · आपकी फ़ाइलें आपके डिवाइस पर ही रहती हैं",
    cta: "अभी शुरू करें — मुफ़्त",
    tools: [
      { name: "इमेज कम्प्रेस करें", desc: "फ़ाइल साइज़ 90% तक कम करें", keyword: "compress image online free hindi" },
      { name: "HEIC से JPG", desc: "iPhone फोटो को JPG में बदलें", keyword: "heic to jpg windows hindi" },
      { name: "PNG से JPG", desc: "PNG को JPG में तुरंत बदलें", keyword: "png to jpg converter free hindi" },
      { name: "पासपोर्ट फ़ोटो", desc: "भारतीय पासपोर्ट फोटो मुफ़्त", keyword: "passport photo online free india" },
      { name: "इमेज रिसाइज़", desc: "किसी भी साइज़ में बदलें", keyword: "image resize online free" },
      { name: "बैकग्राउंड हटाएं", desc: "AI से बैकग्राउंड हटाएं", keyword: "background remove free hindi" },
    ],
    popularSearches: ["इमेज कम्प्रेस", "HEIC से JPG", "पासपोर्ट फ़ोटो", "PNG to JPG", "वॉटरमार्क हटाएं"],
    trustBadges: ["🔒 100% प्राइवेट", "⚡ तुरंत", "🆓 बिल्कुल मुफ़्त", "📵 कोई वॉटरमार्क नहीं"],
    stats: [["5 करोड़+", "फ़ाइलें प्रोसेस की"], ["190+", "देश"], ["4.9★", "रेटिंग"]],
    whyTitle: "Pixalyse क्यों?",
    whyPoints: [
      { icon: "🔒", title: "100% प्राइवेट", desc: "आपकी फ़ाइलें कभी भी किसी सर्वर पर अपलोड नहीं होतीं।" },
      { icon: "⚡", title: "तुरंत परिणाम", desc: "मिलीसेकंड में प्रोसेसिंग, कोई इंतज़ार नहीं।" },
      { icon: "🆓", title: "हमेशा मुफ़्त", desc: "सभी 20 टूल्स, असीमित उपयोग, हमेशा के लिए।" },
    ],
    footerText: "© 2026 Pixalyse · सभी 20 टूल्स हमेशा मुफ़्त · कोई लॉगिन नहीं",
    blogTeaser: "इमेज टिप्स और गाइड",
  },

  // ─── PORTUGUESE (Brazil) ─────────────────────────────────────────────────
  pt: {
    lang: "pt",
    dir: "ltr",
    slug: "pt",
    htmlLang: "pt-BR",
    country: "Brasil",
    flag: "🇧🇷",
    seoTitle: "Pixalyse — Ferramentas de Imagem Online Grátis | Comprimir, Converter, Redimensionar",
    seoDesc: "20 ferramentas de imagem online grátis — comprimir imagem, redimensionar, converter PNG para JPG, HEIC para JPG. Sem login, sem marca d'água. Funciona no navegador.",
    seoKeywords: "comprimir imagem online gratis, converter png para jpg, redimensionar imagem online, heic para jpg gratis, compressor de imagem online brasil, ferramentas imagem gratis",
    headline: "20 Ferramentas de Imagem Grátis",
    subheadline: "Comprimir, Converter, Redimensionar e muito mais — 100% grátis",
    tagline: "Sem login · Sem marca d'água · Seus arquivos ficam no seu dispositivo",
    cta: "Começar Agora — Grátis",
    tools: [
      { name: "Comprimir Imagem", desc: "Reduzir tamanho em até 90%", keyword: "comprimir imagem online gratis" },
      { name: "HEIC para JPG", desc: "Converter fotos do iPhone para JPG", keyword: "converter heic para jpg gratis" },
      { name: "PNG para JPG", desc: "Converter PNG para JPG instantaneamente", keyword: "png para jpg converter gratis" },
      { name: "Foto para Passaporte", desc: "Foto 3x4 e passaporte grátis", keyword: "foto passaporte online gratis brasil" },
      { name: "Redimensionar Imagem", desc: "Qualquer dimensão em pixels", keyword: "redimensionar imagem online gratis" },
      { name: "Remover Fundo", desc: "IA remove o fundo automaticamente", keyword: "remover fundo imagem gratis" },
    ],
    popularSearches: ["Comprimir Imagem", "Remover Fundo", "PNG para JPG", "Foto Passaporte", "Redimensionar"],
    trustBadges: ["🔒 100% Privado", "⚡ Instantâneo", "🆓 Completamente Grátis", "📵 Sem Marca d'Água"],
    stats: [["50M+", "Arquivos Processados"], ["190+", "Países"], ["4.9★", "Avaliação"]],
    whyTitle: "Por que Pixalyse?",
    whyPoints: [
      { icon: "🔒", title: "100% Privado", desc: "Seus arquivos nunca saem do seu dispositivo. Zero uploads para servidores." },
      { icon: "⚡", title: "Resultados Instantâneos", desc: "Processamento em milissegundos, sem esperar fila de servidor." },
      { icon: "🆓", title: "Gratuito Para Sempre", desc: "20 ferramentas, uso ilimitado, sem planos pagos ou créditos." },
    ],
    footerText: "© 2026 Pixalyse · Todas as 20 ferramentas grátis para sempre · Sem login necessário",
    blogTeaser: "Guias e Dicas de Imagem",
  },

  // ─── SPANISH (Spain + LATAM) ──────────────────────────────────────────────
  es: {
    lang: "es",
    dir: "ltr",
    slug: "es",
    htmlLang: "es",
    country: "España / Latinoamérica",
    flag: "🇪🇸",
    seoTitle: "Pixalyse — Herramientas de Imagen Online Gratis | Comprimir, Convertir, Redimensionar",
    seoDesc: "20 herramientas de imagen online gratis — comprimir imagen, redimensionar, convertir PNG a JPG, HEIC a JPG. Sin registro, sin marca de agua. Funciona en el navegador.",
    seoKeywords: "comprimir imagen online gratis, convertir png a jpg gratis, redimensionar imagen online, heic a jpg gratis, compresor de imagen online, herramientas imagen gratis",
    headline: "20 Herramientas de Imagen Gratis",
    subheadline: "Comprimir, Convertir, Recortar, Redimensionar — completamente gratis",
    tagline: "Sin registro · Sin marca de agua · Tus archivos se quedan en tu dispositivo",
    cta: "Empezar Gratis Ahora",
    tools: [
      { name: "Comprimir Imagen", desc: "Reducir tamaño hasta 90%", keyword: "comprimir imagen online gratis" },
      { name: "HEIC a JPG", desc: "Convertir fotos iPhone a JPG", keyword: "convertir heic a jpg gratis" },
      { name: "PNG a JPG", desc: "Convertir PNG a JPG al instante", keyword: "png a jpg convertir gratis" },
      { name: "Foto Pasaporte", desc: "Foto carnet y pasaporte gratis", keyword: "foto pasaporte online gratis" },
      { name: "Redimensionar Imagen", desc: "Cualquier dimensión en píxeles", keyword: "redimensionar imagen online gratis" },
      { name: "Eliminar Fondo", desc: "IA elimina el fondo automáticamente", keyword: "eliminar fondo imagen gratis" },
    ],
    popularSearches: ["Comprimir Imagen", "Eliminar Fondo", "PNG a JPG", "Foto Pasaporte", "Redimensionar"],
    trustBadges: ["🔒 100% Privado", "⚡ Instantáneo", "🆓 Completamente Gratis", "📵 Sin Marca de Agua"],
    stats: [["50M+", "Archivos Procesados"], ["190+", "Países"], ["4.9★", "Valoración"]],
    whyTitle: "¿Por qué Pixalyse?",
    whyPoints: [
      { icon: "🔒", title: "100% Privado", desc: "Tus archivos nunca salen de tu dispositivo. Cero subidas a servidores." },
      { icon: "⚡", title: "Resultados Instantáneos", desc: "Procesamiento en milisegundos, sin esperas." },
      { icon: "🆓", title: "Gratis Para Siempre", desc: "20 herramientas, uso ilimitado, sin planes de pago." },
    ],
    footerText: "© 2026 Pixalyse · Las 20 herramientas gratis para siempre · Sin registro",
    blogTeaser: "Guías y Consejos de Imagen",
  },

  // ─── INDONESIAN ───────────────────────────────────────────────────────────
  id: {
    lang: "id",
    dir: "ltr",
    slug: "id",
    htmlLang: "id-ID",
    country: "Indonesia",
    flag: "🇮🇩",
    seoTitle: "Pixalyse — Alat Gambar Online Gratis | Kompres, Konversi, Ubah Ukuran",
    seoDesc: "20 alat gambar online gratis — kompres gambar, ubah ukuran, konversi PNG ke JPG, HEIC ke JPG. Tanpa login, tanpa watermark. Berjalan di browser.",
    seoKeywords: "kompres gambar online gratis, konversi png ke jpg gratis, ubah ukuran gambar online, heic ke jpg gratis, kompres foto online indonesia, alat gambar gratis",
    headline: "20 Alat Gambar Online Gratis",
    subheadline: "Kompres, Konversi, Potong, Ubah Ukuran — sepenuhnya gratis",
    tagline: "Tanpa login · Tanpa watermark · File Anda tetap di perangkat Anda",
    cta: "Mulai Gratis Sekarang",
    tools: [
      { name: "Kompres Gambar", desc: "Kurangi ukuran file hingga 90%", keyword: "kompres gambar online gratis" },
      { name: "HEIC ke JPG", desc: "Konversi foto iPhone ke JPG", keyword: "konversi heic ke jpg gratis" },
      { name: "PNG ke JPG", desc: "Konversi PNG ke JPG seketika", keyword: "png ke jpg konversi gratis" },
      { name: "Foto Paspor", desc: "Buat foto paspor gratis online", keyword: "foto paspor online gratis" },
      { name: "Ubah Ukuran Gambar", desc: "Dimensi apa pun dalam piksel", keyword: "ubah ukuran gambar online gratis" },
      { name: "Hapus Latar Belakang", desc: "AI hapus latar belakang otomatis", keyword: "hapus latar belakang gambar gratis" },
    ],
    popularSearches: ["Kompres Gambar", "Hapus Latar", "PNG ke JPG", "Foto Paspor", "Ubah Ukuran"],
    trustBadges: ["🔒 100% Pribadi", "⚡ Instan", "🆓 Sepenuhnya Gratis", "📵 Tanpa Watermark"],
    stats: [["50 Juta+", "File Diproses"], ["190+", "Negara"], ["4.9★", "Rating"]],
    whyTitle: "Mengapa Pixalyse?",
    whyPoints: [
      { icon: "🔒", title: "100% Pribadi", desc: "File Anda tidak pernah meninggalkan perangkat Anda. Nol upload ke server." },
      { icon: "⚡", title: "Hasil Instan", desc: "Pemrosesan dalam milidetik, tanpa menunggu." },
      { icon: "🆓", title: "Gratis Selamanya", desc: "20 alat, penggunaan tak terbatas, tanpa paket berbayar." },
    ],
    footerText: "© 2026 Pixalyse · Semua 20 alat gratis selamanya · Tanpa login",
    blogTeaser: "Panduan dan Tips Gambar",
  },

  // ─── ARABIC ───────────────────────────────────────────────────────────────
  ar: {
    lang: "ar",
    dir: "rtl",
    slug: "ar",
    htmlLang: "ar",
    country: "العالم العربي",
    flag: "🌍",
    seoTitle: "Pixalyse — أدوات الصور المجانية | ضغط، تحويل، تغيير الحجم",
    seoDesc: "20 أداة صور مجانية عبر الإنترنت — ضغط الصور، تغيير الحجم، تحويل PNG إلى JPG، HEIC إلى JPG. بدون تسجيل، بدون علامة مائية.",
    seoKeywords: "ضغط الصور مجانا, تحويل png الى jpg, تغيير حجم الصورة, heic to jpg arabic, أدوات صور مجانية, ضغط صورة اون لاين",
    headline: "٢٠ أداة صور مجانية",
    subheadline: "ضغط، تحويل، قص، تغيير الحجم — مجاناً بالكامل",
    tagline: "بدون تسجيل · بدون علامة مائية · ملفاتك تبقى على جهازك",
    cta: "ابدأ مجاناً الآن",
    tools: [
      { name: "ضغط الصورة", desc: "تقليل حجم الملف حتى ٩٠٪", keyword: "ضغط صورة اون لاين مجانا" },
      { name: "HEIC إلى JPG", desc: "تحويل صور iPhone إلى JPG", keyword: "تحويل heic الى jpg مجانا" },
      { name: "PNG إلى JPG", desc: "تحويل PNG إلى JPG فوراً", keyword: "تحويل png الى jpg مجانا" },
      { name: "صورة جواز السفر", desc: "صورة جواز سفر مجانية", keyword: "صورة جواز سفر اون لاين مجانا" },
      { name: "تغيير حجم الصورة", desc: "أي أبعاد بالبكسل", keyword: "تغيير حجم الصورة اون لاين" },
      { name: "إزالة الخلفية", desc: "الذكاء الاصطناعي يزيل الخلفية", keyword: "ازالة خلفية الصورة مجانا" },
    ],
    popularSearches: ["ضغط الصور", "إزالة الخلفية", "PNG إلى JPG", "صورة جواز", "تغيير الحجم"],
    trustBadges: ["🔒 خصوصية ١٠٠٪", "⚡ فوري", "🆓 مجاني تماماً", "📵 بدون علامة مائية"],
    stats: [["٥٠ مليون+", "ملف معالج"], ["١٩٠+", "دولة"], ["٤.٩★", "تقييم"]],
    whyTitle: "لماذا Pixalyse؟",
    whyPoints: [
      { icon: "🔒", title: "خصوصية ١٠٠٪", desc: "ملفاتك لا تغادر جهازك أبداً. صفر تحميلات للخوادم." },
      { icon: "⚡", title: "نتائج فورية", desc: "معالجة في ميلي ثانية، بدون انتظار." },
      { icon: "🆓", title: "مجاني للأبد", desc: "٢٠ أداة، استخدام غير محدود، بدون اشتراكات." },
    ],
    footerText: "© 2026 Pixalyse · جميع الأدوات الـ ٢٠ مجانية للأبد · بدون تسجيل",
    blogTeaser: "أدلة ونصائح الصور",
  },
};
